basePath: /api
definitions:
  handlers.SongAddRequest:
    properties:
      group:
        maxLength: 255
        minLength: 1
        type: string
      song:
        maxLength: 255
        minLength: 1
        type: string
    required:
    - group
    - song
    type: object
  handlers.SongUpdateRequest:
    properties:
      group:
        maxLength: 255
        minLength: 1
        type: string
      link:
        type: string
      release_date:
        type: string
      song:
        maxLength: 255
        minLength: 1
        type: string
      text:
        type: string
    type: object
  models.Song:
    properties:
      group:
        maxLength: 255
        minLength: 1
        type: string
      id:
        type: integer
      link:
        type: string
      release_date:
        type: string
      song:
        maxLength: 255
        minLength: 1
        type: string
      text:
        type: string
    required:
    - group
    - link
    - release_date
    - song
    - text
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API Server for Song Library Application
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Song Library API
  version: "1.0"
paths:
  /songs:
    delete:
      consumes:
      - application/json
      description: Delete existing song
      parameters:
      - description: Group name
        in: query
        name: group
        required: true
        type: string
      - description: Song name
        in: query
        name: song
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete song
      tags:
      - songs
    get:
      consumes:
      - application/json
      description: Get songs with filtering and pagination
      parameters:
      - description: Filter by group name
        in: query
        name: group
        type: string
      - description: Filter by song name
        in: query
        name: song
        type: string
      - description: Filter by release date (YYYY-MM-DD)
        in: query
        name: release_date
        type: string
      - default: 10
        description: Limit number of records
        in: query
        name: limit
        type: integer
      - default: 0
        description: Offset for pagination
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Song'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get songs list
      tags:
      - songs
    post:
      consumes:
      - application/json
      description: Add a new song with details from external API
      parameters:
      - description: Song details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.SongAddRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: integer
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Add new song
      tags:
      - songs
    put:
      consumes:
      - application/json
      description: Update existing song details
      parameters:
      - description: Group name
        in: query
        name: group
        required: true
        type: string
      - description: Song name
        in: query
        name: song
        required: true
        type: string
      - description: Song update details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.SongUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update song
      tags:
      - songs
  /songs/verses:
    get:
      consumes:
      - application/json
      description: Get verses of a specific song with pagination
      parameters:
      - description: Group name
        in: query
        name: group
        required: true
        type: string
      - description: Song name
        in: query
        name: song
        required: true
        type: string
      - default: 5
        description: Limit number of verses
        in: query
        name: limit
        type: integer
      - default: 0
        description: Offset for pagination
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get song verses
      tags:
      - songs
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
